
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/338/bin/cmake/linux/x64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.11.0-24-generic - x86_64
...
